name: Deploy React Vite Project

on:
  push:
    branches:
      - main  # The branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build stopwatch
      run: cd stopwatch && npm install && npm run build

    - name: Deploy stopwatch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: stopwatch/build  # The directory where the build files are located
        publish_branch: gh-pages
